"""Add WorkspaceUsage and update Subscription

Revision ID: 0e9b49028a3f
Revises: 11c3bb9d19ad
Create Date: 2026-08-01 17:11:44.996144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e9b49028a3f'
down_revision: Union[str, None] = '11c3bb9d19ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_usage',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('ai_requests_used', sa.Integer(), nullable=False),
    sa.Column('storage_bytes_used', sa.BigInteger(), nullable=False),
    sa.Column('additional_ai_credits', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_usage_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_usage_workspace_id'), ['workspace_id'], unique=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_cycle', sa.String(length=20), nullable=False, server_default='monthly'))
        batch_op.add_column(sa.Column('plan_price', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('plan_price')
        batch_op.drop_column('billing_cycle')

    with op.batch_alter_table('workspace_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_usage_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_usage_deleted_at'))

    op.drop_table('workspace_usage')
    # ### end Alembic commands ###
