"""Add integrations model

Revision ID: 11c3bb9d19ad
Revises: e94839836dcb
Create Date: 2026-08-01 02:05:27.350031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11c3bb9d19ad'
down_revision: Union[str, None] = 'e94839836dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
