"""add_organization_metrics

Revision ID: 3bff9ba12419
Revises: 
Create Date: 2026-07-22 02:06:19.407647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3bff9ba12419'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_metrics',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('revenue_run_rate', sa.Float(), nullable=False),
    sa.Column('revenue_trend', sa.String(length=255), nullable=False),
    sa.Column('revenue_trend_up', sa.Boolean(), nullable=False),
    sa.Column('revenue_series_json', sa.Text(), nullable=False),
    sa.Column('net_cash_flow', sa.Float(), nullable=False),
    sa.Column('cash_flow_trend', sa.String(length=255), nullable=False),
    sa.Column('cash_flow_trend_up', sa.Boolean(), nullable=False),
    sa.Column('cash_flow_series_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_metrics_org_id'), 'organization_metrics', ['org_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_metrics_org_id'), table_name='organization_metrics')
    op.drop_table('organization_metrics')
    # ### end Alembic commands ###
