"""Add Razorpay fields to Subscription

Revision ID: 5d648179f8ce
Revises: fdc82bd5244f
Create Date: 2026-07-23 11:26:48.123685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d648179f8ce'
down_revision: Union[str, None] = 'fdc82bd5244f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('razorpay_plan_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_razorpay_customer_id'), ['razorpay_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_razorpay_subscription_id'), ['razorpay_subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_razorpay_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_razorpay_customer_id'))
        batch_op.drop_column('razorpay_plan_id')
        batch_op.drop_column('razorpay_customer_id')
        batch_op.drop_column('razorpay_subscription_id')

    # ### end Alembic commands ###
