"""Initial migration

Revision ID: 9e5d677a0833
Revises: 
Create Date: 2026-08-01 20:32:05.968639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e5d677a0833'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_providers',
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_providers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_providers_provider_name'), ['provider_name'], unique=True)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('branding', sa.Text(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('permissions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('organization_domains',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_domains_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_domains_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_organization_domains_organization_id'), ['organization_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('user_security',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_security', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_security_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_security_user_id'), ['user_id'], unique=True)

    op.create_table('user_sessions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('workspaces',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaces_org_id'), ['org_id'], unique=False)

    op.create_table('agent_messages',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(length=30), nullable=False),
    sa.Column('receiver', sa.String(length=30), nullable=False),
    sa.Column('intent', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_receiver'), ['receiver'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_agentruns_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('ix_agentruns_workspace_status', ['workspace_id', 'status'], unique=False)
        batch_op.create_index('ix_agentruns_workspace_trigger', ['workspace_id', 'trigger'], unique=False)
        batch_op.create_index('ix_agentruns_workspace_user', ['workspace_id', 'user_id'], unique=False)

    op.create_table('agent_states',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('agent_key', sa.String(length=30), nullable=False),
    sa.Column('goals_json', sa.Text(), nullable=False),
    sa.Column('observations_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('personality_json', sa.Text(), nullable=False),
    sa.Column('reasoning_history_json', sa.Text(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'agent_key', name='uq_agent_state_workspace_key')
    )
    with op.batch_alter_table('agent_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_states_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_states_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_states_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('agent_tasks',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('agent_key', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('parent_task_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tasks_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_auditlogs_workspace_action', ['workspace_id', 'action'], unique=False)
        batch_op.create_index('ix_auditlogs_workspace_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('background_jobs',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_jobs_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('ix_jobs_workspace_status', ['workspace_id', 'status'], unique=False)
        batch_op.create_index('ix_jobs_workspace_task_type', ['workspace_id', 'task_type'], unique=False)
        batch_op.create_index('ix_jobs_workspace_user', ['workspace_id', 'user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('agent_key', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_conversations_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_conversations_workspace_user', ['workspace_id', 'user_id'], unique=False)

    op.create_table('documents',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_documents_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_documents_workspace_status', ['workspace_id', 'status'], unique=False)
        batch_op.create_index('ix_documents_workspace_type', ['workspace_id', 'file_type'], unique=False)
        batch_op.create_index('ix_documents_workspace_uploader', ['workspace_id', 'uploaded_by'], unique=False)

    op.create_table('integrations',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('memory_records',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('agent_source', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('embedding_id', sa.String(length=36), nullable=True),
    sa.Column('linked_memory_ids', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_memory_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('ix_memory_workspace_kind', ['workspace_id', 'kind'], unique=False)
        batch_op.create_index('ix_memory_workspace_tier', ['workspace_id', 'tier'], unique=False)

    op.create_table('organization_members',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_user_workspace')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('organization_metrics',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('revenue_run_rate', sa.Float(), nullable=False),
    sa.Column('revenue_trend', sa.String(length=255), nullable=False),
    sa.Column('revenue_trend_up', sa.Boolean(), nullable=False),
    sa.Column('revenue_series_json', sa.Text(), nullable=False),
    sa.Column('net_cash_flow', sa.Float(), nullable=False),
    sa.Column('cash_flow_trend', sa.String(length=255), nullable=False),
    sa.Column('cash_flow_trend_up', sa.Boolean(), nullable=False),
    sa.Column('cash_flow_series_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_metrics_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_metrics_workspace_id'), ['workspace_id'], unique=True)

    op.create_table('projects',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('plan_price', sa.Integer(), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_plan_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_razorpay_customer_id'), ['razorpay_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_razorpay_subscription_id'), ['razorpay_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('topics',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('wiki_content', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_usagerecords_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('ix_usagerecords_workspace_metric', ['workspace_id', 'metric_name'], unique=False)

    op.create_table('war_room_sessions',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verdict_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('war_room_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_war_room_sessions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_room_sessions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_features',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_features_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_features_feature_name'), ['feature_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_features_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_invitations',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_invitations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_usage',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('ai_requests_used', sa.Integer(), nullable=False),
    sa.Column('storage_bytes_used', sa.BigInteger(), nullable=False),
    sa.Column('additional_ai_credits', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_usage_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_usage_workspace_id'), ['workspace_id'], unique=True)

    op.create_table('agent_run_outputs',
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('agent_key', sa.String(length=30), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_outputs_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_run_outputs_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('document_chunks',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('memory_topic_links',
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', 'topic_id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('agent_key', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('reports',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('business_health_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risks_json', sa.Text(), nullable=False),
    sa.Column('opportunities_json', sa.Text(), nullable=False),
    sa.Column('recommendations_json', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_reports_workspace_created', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_reports_workspace_user', ['workspace_id', 'user_id'], unique=False)

    op.create_table('war_room_turns',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('responding_to', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('stance', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['war_room_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('war_room_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_war_room_turns_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_room_turns_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('war_room_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_war_room_turns_session_id'))
        batch_op.drop_index(batch_op.f('ix_war_room_turns_deleted_at'))

    op.drop_table('war_room_turns')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_workspace_user')
        batch_op.drop_index(batch_op.f('ix_reports_workspace_id'))
        batch_op.drop_index('ix_reports_workspace_created')
        batch_op.drop_index(batch_op.f('ix_reports_deleted_at'))

    op.drop_table('reports')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    op.drop_table('memory_topic_links')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_deleted_at'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('agent_run_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_outputs_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_agent_run_outputs_agent_run_id'))

    op.drop_table('agent_run_outputs')
    with op.batch_alter_table('workspace_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_usage_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_usage_deleted_at'))

    op.drop_table('workspace_usage')
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_email'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_deleted_at'))

    op.drop_table('workspace_invitations')
    with op.batch_alter_table('workspace_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_features_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_features_feature_name'))
        batch_op.drop_index(batch_op.f('ix_workspace_features_deleted_at'))

    op.drop_table('workspace_features')
    with op.batch_alter_table('war_room_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_war_room_sessions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_war_room_sessions_deleted_at'))

    op.drop_table('war_room_sessions')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index('ix_usagerecords_workspace_metric')
        batch_op.drop_index('ix_usagerecords_workspace_created')
        batch_op.drop_index(batch_op.f('ix_usage_records_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_metric_name'))
        batch_op.drop_index(batch_op.f('ix_usage_records_deleted_at'))

    op.drop_table('usage_records')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_topics_deleted_at'))

    op.drop_table('topics')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_razorpay_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_razorpay_customer_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_deleted_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_session_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_deleted_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_projects_deleted_at'))

    op.drop_table('projects')
    with op.batch_alter_table('organization_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_metrics_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_organization_metrics_deleted_at'))

    op.drop_table('organization_metrics')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_role_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_org_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_deleted_at'))

    op.drop_table('organization_members')
    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_workspace_tier')
        batch_op.drop_index('ix_memory_workspace_kind')
        batch_op.drop_index('ix_memory_workspace_created')
        batch_op.drop_index(batch_op.f('ix_memory_records_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_memory_records_tier'))
        batch_op.drop_index(batch_op.f('ix_memory_records_deleted_at'))

    op.drop_table('memory_records')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_provider'))
        batch_op.drop_index(batch_op.f('ix_integrations_deleted_at'))

    op.drop_table('integrations')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_workspace_uploader')
        batch_op.drop_index('ix_documents_workspace_type')
        batch_op.drop_index('ix_documents_workspace_status')
        batch_op.drop_index(batch_op.f('ix_documents_workspace_id'))
        batch_op.drop_index('ix_documents_workspace_created')
        batch_op.drop_index(batch_op.f('ix_documents_deleted_at'))

    op.drop_table('documents')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_workspace_user')
        batch_op.drop_index(batch_op.f('ix_conversations_workspace_id'))
        batch_op.drop_index('ix_conversations_workspace_created')
        batch_op.drop_index(batch_op.f('ix_conversations_deleted_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_workspace_user')
        batch_op.drop_index('ix_jobs_workspace_task_type')
        batch_op.drop_index('ix_jobs_workspace_status')
        batch_op.drop_index('ix_jobs_workspace_created')
        batch_op.drop_index(batch_op.f('ix_background_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_deleted_at'))

    op.drop_table('background_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_auditlogs_workspace_created')
        batch_op.drop_index('ix_auditlogs_workspace_action')
        batch_op.drop_index(batch_op.f('ix_audit_logs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_api_keys_created_by'))

    op.drop_table('api_keys')
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tasks_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_agent_key'))

    op.drop_table('agent_tasks')
    with op.batch_alter_table('agent_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_states_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_states_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_agent_states_agent_key'))

    op.drop_table('agent_states')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_agentruns_workspace_user')
        batch_op.drop_index('ix_agentruns_workspace_trigger')
        batch_op.drop_index('ix_agentruns_workspace_status')
        batch_op.drop_index('ix_agentruns_workspace_created')
        batch_op.drop_index(batch_op.f('ix_agent_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_deleted_at'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_sender'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_receiver'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_execution_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_deleted_at'))

    op.drop_table('agent_messages')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_org_id'))
        batch_op.drop_index(batch_op.f('ix_workspaces_deleted_at'))

    op.drop_table('workspaces')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_deleted_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_security', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_security_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_security_deleted_at'))

    op.drop_table('user_security')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_deleted_at'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('organization_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_domains_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_domains_domain'))
        batch_op.drop_index(batch_op.f('ix_organization_domains_deleted_at'))

    op.drop_table('organization_domains')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_deleted_at'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_deleted_at'))

    op.drop_table('permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_deleted_at'))

    op.drop_table('organizations')
    with op.batch_alter_table('oauth_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_providers_provider_name'))
        batch_op.drop_index(batch_op.f('ix_oauth_providers_deleted_at'))

    op.drop_table('oauth_providers')
    # ### end Alembic commands ###
