"""Add BackgroundJob table

Revision ID: cb93f45fb74f
Revises: 5d648179f8ce
Create Date: 2026-07-23 11:50:21.718629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb93f45fb74f'
down_revision: Union[str, None] = '5d648179f8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
