"""Add invite_token to Workspace

Revision ID: d478d3b436c6
Revises: 9e5d677a0833
Create Date: 2026-08-02 02:28:57.025836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd478d3b436c6'
down_revision: Union[str, None] = '9e5d677a0833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_token', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_workspaces_invite_token'), ['invite_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_invite_token'))
        batch_op.drop_column('invite_token')

    # ### end Alembic commands ###
