"""Add WarRoom models

Revision ID: e94839836dcb
Revises: cb93f45fb74f
Create Date: 2026-07-24 01:21:10.729005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e94839836dcb'
down_revision: Union[str, None] = 'cb93f45fb74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_room_sessions',
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verdict_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('war_room_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_war_room_sessions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_room_sessions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('war_room_turns',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('responding_to', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('stance', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['war_room_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('war_room_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_war_room_turns_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_room_turns_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('war_room_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_war_room_turns_session_id'))
        batch_op.drop_index(batch_op.f('ix_war_room_turns_deleted_at'))

    op.drop_table('war_room_turns')
    with op.batch_alter_table('war_room_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_war_room_sessions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_war_room_sessions_deleted_at'))

    op.drop_table('war_room_sessions')
    # ### end Alembic commands ###
